lua/neotest-java/core/result_builder.lua, tests/core/result_builder_spec.lua, tests/fixtures/maven-demo/src/test/java/com/example/ErroneousTest.java
I noticed that the adapter will show tests succeeded if an error occurred when trying to start a test but there is an error. In this case in the xml file there will be an `<error>` tag instead of a `<failure>` tag. Because of this the failure wouldn't be caught and so it would go to the else and show it as succeeding. This is to fix this issue.
=> Prevent false positives when test fails to start because of an error

lua/neotest-java/init.lua, tests/core/spec_builder_spec.lua, tests/init_spec.lua
I found out that it was not using the default configuration when it was not specified.
Example:
```lua
require("neotest").setup({
adapters = {
require("neotest-java"),
}
})
``` 
This PR fix it.
=> fix: use default configuration when not specified

lua/neotest-java/core/positions_discoverer.lua, lua/neotest-java/init.lua, tests/core/positions_discoverer_spec.lua, tests/core/result_builder_spec.lua, tests/fixtures/SomeNestedTest.java, tests/fixtures/gradle-demo/src/test/java/com/example/NestedTests.java, tests/fixtures/maven-demo/src/test/java/com/example/NestedTests.java
~~Fixes #54~~
This will allow neotest to identify classes as namespaces and will make #54 easier to resolve.
=> feat: added classes as namespaces to the treesitter query

lua/neotest-java/core/spec_builder.lua
When added namespaces to the treesitter query, it started to take the namespace tree node as the first node, affecting the behavior of the `spec_builder`.
This is a little hack until #54 gets resolved.
=> fix: temporary fix for treesitter query impacting spec_builder behavior

lua/neotest-java/core/result_builder.lua, tests/core/result_builder_spec.lua
What all names given by JUnit reports to parameterized tests have in common is that they have:
* the name of the function
* some characthers in the middle starting with `[` or `{`
* ends with the index of the testcase inside square brackets.
=> fix: parameterized test regex

lua/neotest-java/core/positions_discoverer.lua
JUnit Pioneer is an extension of JUnit 5 and has a `@CartesianTest` annotation that allows for multiple parameters (instead of a single parameter in the traditional `@ParameterizedTest`.)
This PR adds support for that new annotation.
Ref: https://junit-pioneer.org/docs/cartesian-product/
=> Add support for JUnit Pioneer's @CartesianTest

lua/neotest-java/core/dir_filter.lua, lua/neotest-java/core/file_checker.lua
1. there was no reason for those to be global variables
2. having it local avoids annoying race conditions
=> fix: avoid race conditions on global variables

plugin/neotest-java.lua
=> fix: prevent fail for non existing dir on setup

lua/neotest-java/build_tool/gradle.lua, lua/neotest-java/build_tool/init.lua, lua/neotest-java/build_tool/maven.lua, lua/neotest-java/command/junit_command_builder.lua
Related: #98 
Added all filepaths of the java classes for the `javac` command to avoid using globs as it is not compatible in all systems.
=> pass all java class filepaths to javac command

lua/neotest-java/command/junit_command_builder.lua
Set the IP address for compatibility with older version not supporting `*:`.
Also adding `-Xdebug` arg as [java documentation](https://docs.oracle.com/en/java/javase/21/docs/specs/man/java.html) says: 
> Does nothing. Provided for backward compatibility.
For reference: 
* https://github.com/OpenLiberty/open-liberty/issues/7833
* https://github.com/sedici/docker-dspace/commit/63dbdac4c99575e4854e756687b1234948e6f9dc
=> fix: explicit address for compatibility

lua/neotest-java/build_tool/maven.lua
I've faced an issue that leads a test execution to the error because classpath.txt do not exist in target directory.
I've found that the row which I'm proposing to return back have been removed at commit 48efda01d1b9daff8c15322631f26b533d005336 . I presume it was done by mistake
=> Bugfix: Test execution stuck if a maven project do not have the neotest-java directory (first execution or after the mvn clean)

lua/neotest-java/build_tool/init.lua, lua/neotest-java/command/junit_command_builder.lua
Hello,
most frameworks are using reflection mechanism to automatically detect a variable by its name (for example Spring's `@PathVariable`), and in order to make it work we have to compile the tests using the `-parameters` flag, otherwise the parameter's information will be skipped at compilation time and the tests will fail.
This simple PR adds the `-parameters` flag to the compilation phase.
=> Add -parameters flag

lua/neotest-java/build_tool/maven.lua
Problem fix for an infinite loop on my Macbook. Might be an OS Specific thing.
This call to cat leads to an infinite loop and a never ending process, unless i manually add a newline char at the end of the file This fix uses the existing utility function and seems to work like a charm.
=> Use read_file from utils instead of OS cat

lua/neotest-java/build_tool/init.lua, lua/neotest-java/core/result_builder.lua
Using nvim 0.10, I'm getting 
```
E5560: nvim_echo must not be called in a lua loop callback
```
Pointing to this vim.notify call. I'm assuming it's safe to change for a log.error.
=> Remove call to vim.notify within loop callback

lua/neotest-java/build_tool/init.lua
=> fix(dap): add missing debug symbols to debug compilation command

lua/neotest-java/core/result_builder.lua, lua/neotest-java/core/spec_builder.lua, lua/neotest-java/util/flat_map.lua, tests/core/result_builder_spec.lua
Content: 
- spec_builder now just returns the reports_dir instead of a path to a file
- result_builder now builds results for all the possible report files
=> Add support for processing junit4 reports from TEST-junit-vintage.xml

README.md
It looks like there is a missing comma in the README regarding the lazy.nvim installation.
=> fix: Add missing comma in README.md

lua/neotest-java/command/jdtls.lua, lua/neotest-java/command/junit_command_builder.lua
=> fix: add resources for junit command

lua/neotest-java/core/spec_builder.lua, lua/neotest-java/types/project.lua, lua/neotest-java/util/write_file.lua
=> fix: remove incorrect use of plenary.path

lua/neotest-java/types/test_class_patterns.lua, lua/neotest-java/util/resolve_qualified_name.lua, tests/util/resolve_qualified_name_spec.lua
Fixes #161 
The problem was that there were several classes in the same test file at level zero and the first was being taken.
Example:
```java
// Filename: ApplicationTests.java
@TestConfiguration
class TestConfig {
@Bean
public String someBean() {
return "some bean";
}
}
@SpringBootTest
class ApplicationTests {
@Test
void contextLoads() {
}
}
```
It was resolved by filtering non-test class names.
=> fix: multiple classes at level zero

lua/neotest-java/core/root_finder.lua, lua/neotest-java/init.lua, tests/core/root_finder_spec.lua
Refactored the `root_finder.find_root` function to accept a matcher function as a second argument, inverting the dependency. Updated the corresponding call in `init.lua` to pass the matcher function. Adjusted tests to reflect the new function signature.
=> refactor: invert depencencies for root_finder

lua/neotest-java/core/file_checker.lua, tests/core/dir_filter_spec.lua, tests/core/file_checker_spec.lua
So I had a project where we have a package named "domain" and the pattern just ignored all our test files in that package.
I have a fix for that it should work if we assume we always have everything in a sub directory like "src".
=> fix: only ignore the main directory files
